package
{
	import flash.geom.Point;		import normal.GameState;		import org.flixel.*;

	public class PlayState extends FlxState
	{		[Embed('img/normalness-bar.png')]	private var normalBarImage : Class;		[Embed('img/ccs.png')]		private var bgImage : Class;		[Embed('img/fountain.png')]		private var fountainImage : Class;		[Embed('img/cursor.png')]	private var cursorImage : Class;				public var gameState : GameState;				public var barImage : FlxSprite;		public var normalBar : FlxSprite;		public var bgSprite : FlxSprite;		public var fountainSprite : FlxSprite;		public var cursorSprite : FlxSprite;		public var carSprites : Array;				public var cursorPos : Point;				public var freeway1Layer : FlxLayer;		public var freeway2Layer : FlxLayer;		public var fireLayer : FlxLayer;		public var personLayer : FlxLayer;		public var barLayer : FlxLayer;		public var cursorLayer : FlxLayer;		
		public function PlayState()
		{			gameState = GameState.getInstance();			gameState.state = this;			gameState.start();			cursorPos = new Point(25, 10);						bgSprite = new FlxSprite(0, 0, bgImage);			add(bgSprite);						fountainSprite = new FlxSprite(12, 13);			fountainSprite.loadGraphic(fountainImage, true, false, 5, 4);			fountainSprite.addAnimation("normal", [0, 1, 2], 10, true);			fountainSprite.play("normal");			add(fountainSprite);								barImage = new FlxSprite(50, 0, normalBarImage);			normalBar = new FlxSprite(51, 0);						freeway1Layer = new FlxLayer(); add(freeway1Layer);			freeway2Layer = new FlxLayer(); add(freeway2Layer);			fireLayer = new FlxLayer(); add(fireLayer);			personLayer = new FlxLayer(); add(personLayer);			cursorLayer = new FlxLayer(); add(cursorLayer);			barLayer = new FlxLayer(); add(barLayer);						barLayer.add(barImage);			barLayer.add(normalBar);						cursorSprite = new FlxSprite(cursorPos.x, cursorPos.y, cursorImage);			cursorLayer.add(cursorSprite);						carSprites = gameState.cars;			carSprites.forEach(function (i:*, n:int, a:Array) : void { if (i.velocity.x > 0) freeway2Layer.add(i); else freeway1Layer.add(i);});
		}		override public function update():void		{			cursorPos.x = FlxG.mouse.x;			cursorPos.y = FlxG.mouse.y;						cursorSprite.x = cursorPos.x-1;			cursorSprite.y = cursorPos.y-1;						gameState.update();						if (gameState.gameOver) {				FlxG.switchState(GameOverState);			}						drawNormalness();						if(FlxG.mouse.justPressed()) {				//trace("Hola x:" + FlxG.mouse.x + " y:"+FlxG.mouse.y);				gameState.fire(cursorSprite);			}						super.update();		}				private function drawNormalness() : void {			var h : int = Math.ceil(gameState.normalness/gameState.MAX_NORMALNESS*16);						if (h >0) {				normalBar.visible = true;				normalBar.createGraphic(3, h, 0x66ff0000);				if (gameState.normalness == gameState.MAX_NORMALNESS) {					normalBar.pixels.setPixel32(0, 0, 0xffffffff);					normalBar.pixels.setPixel32(1, 0, 0xffffffff);					normalBar.pixels.setPixel32(2, 0, 0xffffffff);				}								normalBar.y = (16-h);			} else {				normalBar.visible = false;
			}
		}
	}
}
